Archive/2BlogLy/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }

  root "posts#all"

  resources :users, only: [] do
    resources :posts
  end

  resources :comments, only: [:create]

end

Archive/2BlogLy/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

Archive/2BlogLy/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	validates :post_text,
		presence: true

	validates :cover_image,
		presence: true
end

Archive/2BlogLy/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "temp/profile-pic.jpg", :storage => :s3, :bucket => "bucketname"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  has_many :posts
  has_many :comments
end

Archive/2BlogLy/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		comment = current_user.comments.create(comment_params)

		if comment.valid?
			redirect_to :back
		else
			flash[:error] = "There was a problem saving the comment."
			redirect_to :back
		end
	end

private

	def comment_params
		params.require(:comment).permit(:comment_text, :post_id)
	end

end

Archive/2BlogLy/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:all, :show]

	def all
		if params[:q]
			@posts = Post.where("post_title LIKE ? OR post_text LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%").order(created_at: :desc).paginate(:page => params[:page], :per_page => 4)
		else
			@posts = Post.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 4)
		end
	end

	def index
		@posts = Post.where(user_id: params[:user_id]).paginate(:page => params[:page], :per_page => 4)
	end

	def new
		@post = Post.new
		@user = User.find(params[:user_id])
	end

	def create
		post = User.find(params[:user_id]).posts.create(post_params)

		if post.valid?
			redirect_to user_posts_path(current_user.id)
		else
			flash[:error] = "Post could not be saved."
			redirect_to :back
		end
	end

	def show
		@post = Post.find(params[:id])
		@author = User.find(params[:user_id])

		@comment = Comment.new
		@comments = Comment.where(post_id: params[:id]).order(created_at: :desc)
	end

private

	def post_params
		params.require(:post).permit(:post_text, :cover_image, :post_title)
	end

end

Archive/2BlogLy/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :username, :about_me, :avatar)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :username, :about_me, :avatar)
    end

end

Archive/2BlogLy/app/helpers/comments_helper.rb
module CommentsHelper
end

Archive/2BlogLy/app/helpers/posts_helper.rb
module PostsHelper

	def get_author_name(user_id)
		user = User.find(user_id)

		return user.first_name + " " + user.last_name
	end

end

Archive/2BlogLy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogLy</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
</head>
<body>

<%= render "partials/navbar" %>

<%= yield %>

<!-- jQuery -->
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<%= javascript_include_tag 'application' %>

</body>
</html>

Archive/2BlogLy/app/views/partials/_footer.html.erb
<% if user_signed_in? %>
	<!-- Footer -->
	<footer>
	    <div class="row">
	        <div class="col-lg-12">
	            <p>Copyright &copy; <%= current_user.first_name %> <%= current_user.last_name %> 2015</p>
	        </div>
	    </div>
	    <!-- /.row -->
	</footer>
<% end %>

Archive/2BlogLy/app/views/partials/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog.Ly</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if user_signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <%= current_user.last_name %> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/">All Posts</a>
                            </li>
                            <li><%= link_to "New Post", new_user_post_path(current_user.id) %></li>
                            <li><%= link_to "My Posts", user_posts_path(current_user.id) %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Log Out", destroy_user_session_path, method: "DELETE" %></li>
                        </ul>
                    </li>
                </ul>
            <% end %>

            <% if !user_signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "Log In", new_user_session_path %>
                    </li>
                </ul>
            <% end %>            
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

Archive/2BlogLy/app/views/partials/_search.html.erb
<%= form_tag(root_path, method: "GET") do %>
	<!-- Blog Search Well -->
	<div class="well">
		<h4>Blog Search</h4>
		<div class="input-group">
			<input type="text" class="form-control" name="q">
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit">
					<span class="glyphicon glyphicon-search"></span>
				</button>
			</span>
		</div>
		<!-- /.input-group -->
	</div>
<% end %>

Archive/2BlogLy/app/views/posts/all.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                All Posts
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <% @posts.each do |post| %>
        <hr>

        <!-- Post One -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="<%= post.cover_image %>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3><%= post.post_title %></h3>
                <%= simple_format(post.post_text) %>
                <a class="btn btn-primary" href="<%= user_post_path(post.user_id, post.id) %>">View Post <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->
    <% end %>

    <hr>

    <!-- Pagination -->
    <div class="text-center">
        <%= will_paginate(@posts) %>
    </div>
    <!-- /.row -->

    <hr>

    <%= render "partials/footer" %>

</div>
<!-- /.container -->

Archive/2BlogLy/app/views/posts/index.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%= current_user.first_name %>'s Blog
                <small>@<%= current_user.username %></small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <% @posts.each do |post| %>
        <hr>

        <!-- Post One -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="<%= post.cover_image %>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3><%= post.post_title %></h3>
                <%= simple_format(post.post_text) %>
                <a class="btn btn-primary" href="<%= user_post_path(current_user.id, post.id) %>">View Post <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->
    <% end %>

    <hr>

    <!-- Pagination -->
    <div class="text-center">
        <%= will_paginate(@posts) %>
    </div>
    <!-- /.row -->

    <hr>

    <%= render "partials/footer" %>

</div>
<!-- /.container -->

Archive/2BlogLy/app/views/posts/new.html.erb
<!-- Page Content -->
<div class="container">

	<div class="row">

		<!-- Blog Post Content Column -->
		<div class="col-lg-8">

			<!-- Blog Post -->

			<%= form_for [@user, @post] do |f| %>

				<!-- Title -->
				<h1>New Post</h1>

				<hr>

				<div>
					<%= f.text_field :post_title, class: "form-control", placeholder: "Post Title" %>
				</div>

				<%= f.text_area :post_text, class: "form-control margin-top-20", placeholder: "Your Post", rows: 10 %>

				<div class="margin-top-20">
					<%= f.text_field :cover_image, class: "form-control", placeholder: "Blog Image" %>
				</div>

				<div class="margin-top-20">
					<%= f.submit "Submit Post", class: "btn btn-primary" %>
				</div>
			<% end %>

		</div>

		<!-- Blog Sidebar Widgets Column -->
		<div class="col-md-4">

			<%= render "partials/search" %>

			<!-- Side Widget Well -->
			<div class="well">
				<h4>Post Tips</h4>
				<p>Write well and don't forget to be funny!</p>
			</div>

		</div>

	</div>
	<!-- /.row -->

	<hr>

	<%= render "partials/footer" %>

</div>
<!-- /.container -->

Archive/2BlogLy/app/views/posts/show.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Post Content Column -->
        <div class="col-lg-8">

            <!-- Blog Post -->

            <!-- Title -->
            <h1><%= @post.post_title %></h1>

            <!-- Author -->
            <p class="lead">
                by <%= @author.first_name %> <%= @author.last_name %>
            </p>

            <hr>

            <!-- Date/Time -->
            <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @post.created_at.strftime("%B %-d, %Y") %></p>

            <hr>

            <!-- Preview Image -->
            <img class="img-responsive" src="<%= @post.cover_image %>" alt="">

            <hr>

            <!-- Post Content -->
            <p><%= simple_format(@post.post_text) %></p>

            <hr>

            <!-- Blog Comments -->
            <% if user_signed_in? %>
                <%= form_for @comment do |f| %>
                    <!-- Comments Form -->
                    <div class="well">
                        <h4>Leave a Comment:</h4>
                        <div class="form-group">
                            <%= f.hidden_field :post_id, value: params[:id] %>
                            <%= f.text_area :comment_text, placeholder: "Your Comment", class: "form-control" %>
                        </div>
                        <%= f.submit "Submit Comment", class: "btn btn-primary" %>
                    </div>
                <% end %>
            <% end %>

            <hr>

            <!-- Posted Comments -->

            <% @comments.each do |comment| %>
                <!-- Comment -->
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading"><%= get_author_name(comment.user_id) %>
                            <small><%= comment.created_at.strftime("%B %-d, %Y") %></small>
                            <p><%= image_tag User.find(comment.user_id).avatar.url(:thumb) %> </p>
                        </h4>
                        <%= comment.comment_text %>
                        <hr>
                    </div>
                </div>
            <% end %>

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

            <%= render "partials/search" %>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>About the Author</h4>
                <img class="img-responsive img-circle" src="<%= @author.avatar.url %>" />
                <p><%= simple_format(@author.about_me) %></p>
            </div>

        </div>

    </div>
    <!-- /.row -->

    <hr>